add if/else

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -17,30 +17,25 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Build docs
-        run: |
-          sudo apt-get install pandoc
-          make build_docs
-
-      - name: Ensure version is bumped
-        id: check_version
-        run: |
-          # Ensure we have a valid HEAD^
-          if ! git rev-parse --verify HEAD^ >/dev/null 2>&1; then
-            echo "Error: Cannot check version bump. Ensure the repository has at least two commits."
-            exit 1
-          fi
-          
-          # Check if the VERSION file was updated
-          if ! git diff --name-only HEAD^ HEAD | grep -q "VERSION"; then
-            echo "Error: VERSION must be updated to bump the version for a new release."
-            exit 1
-          fi
-          
-          # Read the new version
-          VERSION=$(cat VERSION)
-          echo "version=$VERSION" >> $GITHUB_ENV
-          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Ensure VERSION is available
+#      - name: Ensure version is bumped
+#        id: check_version
+#        run: |
+#          # Ensure we have a valid HEAD^
+#          if ! git rev-parse --verify HEAD^ >/dev/null 2>&1; then
+#            echo "Error: Cannot check version bump. Ensure the repository has at least two commits."
+#            exit 1
+#          fi
+#
+#          # Check if the VERSION file was updated
+#          if ! git diff --name-only HEAD^ HEAD | grep -q "VERSION"; then
+#            echo "Error: VERSION must be updated to bump the version for a new release."
+#            exit 1
+#          fi
+#
+#          # Read the new version
+#          VERSION=$(cat VERSION)
+#          echo "version=$VERSION" >> $GITHUB_ENV
+#          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Ensure VERSION is available
 
       # Step 3: Build the Go project for Linux, macOS, and Windows
       - name: Build Go project for Linux, macOS (arm64), and Windows
@@ -55,6 +50,11 @@ jobs:
 
           # Build for Windows amd64
           GOOS=windows GOARCH=amd64 go build -o dist/TimecodeTool-windows-amd64.exe cmd/TimecodeTool/main.go
+
+      - name: build docs
+        run: |
+          sudo apt-get install pandoc
+          make build_docs
 
       # Step 4: Tag the release
       - name: Create release tag
