update wf

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -18,10 +18,16 @@ jobs:
       - name: Ensure version is bumped
         id: check_version
         run: |
+          if [ "$(git rev-list --count HEAD)" -eq 1 ]; then
+            echo "Error: Cannot check version bump on the first commit."
+            exit 1
+          fi
+          
           if ! git diff --name-only HEAD^ HEAD | grep -q "VERSION"; then
             echo "Error: VERSION must be updated to bump the version for a new release."
             exit 1
           fi
+          
           VERSION=$(cat VERSION)
           echo "version=$VERSION" >> $GITHUB_ENV
 
